name: Run tests

on:
  push:
  schedule:
  - cron: '0 2 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.ref != 'refs/heads/master' || github.run_number }}
  cancel-in-progress: true

jobs:
  job1:
    name: "Get tutorials list"
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - uses: actions/checkout@v4
    - id: set-matrix
      run: |
        echo "::set-output name=matrix::{\"node\":[$(python getter.py)]}"
  job2:
    needs:
    - job1
    name: "Run tests"
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJSON(needs.job1.outputs.matrix)}}
    steps:
    - uses: actions/checkout@v4
    - name: "Set up Julia"
      uses: julia-actions/setup-julia@v1
      with:
        version: '1.10'
    - name: "Install Jupyter"
      run: pip3 install notebook jupytext
    - name: "Install julia pre-requisites"
      run: |
        julia -e '
          using Pkg
          Pkg.add("IJulia")
          Pkg.add("Oscar")
          Pkg.add("BenchmarkTools")
          Pkg.add("GraphRecipes")
          Pkg.add("Graphs")
          Pkg.add("Interact")
          Pkg.add("Plots")'
    - run: mkdir -pv notebooks
    - run: python3 tester.py ${{ matrix.node }}
      continue-on-error: true
    - name: Upload new notebook
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.node }}
        path: notebooks/*.ipynb
        retention-days: 7
